function response = query_patient_chatbot(userQuery, patientData, currentPrediction, etdrsReport, activeLang)
% QUERY_PATIENT_CHATBOT Intelligent clinical conversational AI co-pilot for Diabetic Retinopathy
% Answers EXACTLY what is asked:
%   - Disease education & pathology (What is DR, microaneurysms, exudates, DME, blindness)
%   - Today's scan triage & diagnosis (Grade, referability, urgency, confidence)
%   - Patient longitudinal EHR history (HbA1c, BP, prior treatments, medications, visits)
%   - Evidence-based clinical guidelines (ICMR / AIIMS protocols, diet, laser, injections)
%   - Seamless bilingual reasoning (English, Hindi, Marathi, Kannada, Tamil, Telugu)
%
% Syntax:
%   response = query_patient_chatbot(userQuery, patientData, currentPrediction, etdrsReport, activeLang)
%
% SIH Problem Statement 26038 | MathWorks Track

    if nargin < 2 || isempty(patientData)
        patientData = struct('patientId', 'IND-PHC-2026-0814', 'patientName', 'Ramesh Kumar', 'age', 58, 'sex', 'Male');
    end
    if nargin < 3
        currentPrediction = [];
    end
    if nargin < 4
        etdrsReport = [];
    end
    if nargin < 5 || isempty(activeLang)
        activeLang = 'en';
    end

    pId = 'IND-PHC-2026-0814';
    pName = 'Ramesh Kumar';
    if isfield(patientData, 'patientId'), pId = patientData.patientId; end
    if isfield(patientData, 'patientName'), pName = patientData.patientName; end

    % Fetch complete longitudinal EHR record
    ehr = patient_ehr_database(pId, pName);

    % Normalize query string
    q = lower(strtrim(userQuery));

    % Auto-detect language
    isHindi = strcmp(activeLang, 'hi') || contains(q, {'हिन्दी', 'hindi', 'मरीज', 'इतिहास', 'दौरा', 'शुगर', 'उपचार', 'दवा', 'क्या', 'है', 'कैसे', 'आँख', 'रेटिना'});
    isMarathi = strcmp(activeLang, 'mr') || contains(q, {'मराठी', 'marathi', 'रुग्ण', 'तपासणी', 'औषध'});

    % =========================================================================
    % LIVE AI API INTEGRATION (GOOGLE GEMINI REST API VIA WEBWRITE)
    % =========================================================================
    configPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'api_config.json');
    apiConfig = struct('gemini_api_key', '', 'model', 'gemini-2.5-flash', 'use_live_api', false);
    if exist(configPath, 'file')
        try
            raw = fileread(configPath);
            apiConfig = jsondecode(raw);
        catch
        end
    end

    envKey = getenv('GEMINI_API_KEY');
    hasKey = (~isempty(apiConfig.gemini_api_key) && strlength(strtrim(apiConfig.gemini_api_key)) > 5) || (~isempty(envKey) && strlength(strtrim(envKey)) > 5);
    isLiveEnabled = (isfield(apiConfig, 'use_live_api') && apiConfig.use_live_api) || ~isempty(envKey);

    if hasKey && isLiveEnabled
        try
            geminiResp = call_gemini_api(userQuery, ehr, currentPrediction, etdrsReport, activeLang, apiConfig);
            if ~isempty(geminiResp) && strlength(strtrim(geminiResp)) > 10
                response = geminiResp;
                return;
            end
        catch
            % Seamless fallback to Precision Offline Engine
        end
    end

    % ---------------------------------------------------------------------
    % INTENT 1: GREETINGS & INTRODUCTORY QUERIES
    % ---------------------------------------------------------------------
    if any(strcmp(q, {'hi', 'hello', 'hey', 'namaste', 'halo', 'help', 'who are you', 'what can you do', 'menu'})) || ...
       contains(q, {'नमस्ते', 'हेलो', 'हाय', 'आप कौन हैं', 'मदद'})
        if isHindi
            response = sprintf(['🤖 **नमस्ते! मैं रेटिनाकेयर एआई का क्लिनिकल को-पायलट हूँ।**\n\n' ...
                'मैं मरीज़ **%s** (%s) की रेटिना रिपोर्ट और मेडिकल रिकॉर्ड के किसी भी प्रश्न का सटीक उत्तर दे सकता हूँ:\n\n' ...
                '📌 **आप मुझसे सीधे पूछ सकते हैं:**\n' ...
                '• **रोग व स्थिति:** "मरीज को क्या बीमारी है?", "आज का ग्रेड और निदान क्या है?"\n' ...
                '• **रेफरल व अस्पताल:** "क्या मरीज को रेफर करना चाहिए?", "रेफरल कितना जरूरी है?"\n' ...
                '• **मरीज का इतिहास:** "मरीज का HbA1c और शुगर क्या है?", "बीपी और दवाइयाँ क्या हैं?"\n' ...
                '• **लक्षण व पैथोलॉजी:** "माइक्रोएन्यूरिज्म क्या होता है?", "हार्ड एक्जुडेट क्या हैं?"\n' ...
                '• **इलाज व रोकथाम:** "ग्रेड 2 का इलाज क्या है?", "क्या अंधापन हो सकता है?"'], ...
                ehr.name, ehr.id);
        else
            response = sprintf(['🤖 **Hello! I am the RetinaCare AI Clinical Decision Co-Pilot.**\n\n' ...
                'I provide direct, precise clinical answers regarding patient **%s** (ID: %s) and retinal fundus findings:\n\n' ...
                '📌 **Questions you can ask directly:**\n' ...
                '• **Disease & Diagnosis:** "What disease does the patient have?", "What is today''s DR grade?"\n' ...
                '• **Triage & Referral:** "Is this patient referable?", "How urgent is the referral?"\n' ...
                '• **EHR History:** "What is the patient''s HbA1c?", "What medications are they taking?"\n' ...
                '• **Pathology:** "What is a microaneurysm?", "What are hard exudates?"\n' ...
                '• **Clinical Care:** "What treatment is recommended?", "Can this cause blindness?"'], ...
                ehr.name, ehr.id);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 2A: DISEASE IDENTITY & CURRENT CLINICAL CONDITION
    % (e.g. "what disease", "disease", "condition", "what is wrong", "illness")
    % ---------------------------------------------------------------------
    if contains(q, {'what disease', 'disease', 'condition', 'illness', 'what is wrong', 'problem', ...
                   'what do i have', 'what does patient have', 'what does he have', 'what does she have', ...
                   'बीमारी', 'रोग', 'क्या हुआ है', 'क्या बीमारी है', 'बीमारी क्या है'})
        if ~isempty(currentPrediction)
            g = currentPrediction.grade;
            gName = currentPrediction.gradeName;
            conf = currentPrediction.confidence * 100;
            urg = currentPrediction.referralUrgency;
            isRef = currentPrediction.isReferable;
            
            if isHindi
                response = sprintf(['👁️ **रोग व वर्तमान स्थिति (Disease & Clinical Diagnosis):**\n\n' ...
                    'मरीज़ को **डायबिटिक रेटिनोपैथी (Diabetic Retinopathy)** है, जो वर्तमान में **ग्रेड %d — %s** की अवस्था में है।\n\n' ...
                    '• **मुख्य रोग:** डायबिटिक रेटिनोपैथी (लंबे समय तक अनियंत्रित शुगर से आँख के पर्दे/रेटिना की नसों को होने वाली क्षति)\n' ...
                    '• **वर्तमान गंभीरता:** **ग्रेड %d (%s)** (एआई सटीकता: %.1f%%)\n' ...
                    '• **रेफरल स्थिति:** **%s** (तात्कालिकता: %s)\n' ...
                    '• **क्लिनिकल अर्थ:** %s\n' ...
                    '• **उपचार सलाह:** %s'], ...
                    g, gName, g, gName, conf, ...
                    ternary(isRef, 'हाँ — नेत्र विशेषज्ञ को रेफरल अनिवार्य', 'नहीं — नियमित वार्षिक निगरानी'), ...
                    urg, get_grade_explanation(g, 'hi'), get_referral_advice(g, 'hi'));
            else
                response = sprintf(['👁️ **PRIMARY DIAGNOSIS & DISEASE IDENTITY:**\n\n' ...
                    'The patient has **Diabetic Retinopathy (DR)**, currently staged at **Grade %d — %s**.\n\n' ...
                    '• **Primary Disease:** Diabetic Retinopathy (Microvascular end-organ damage caused by chronic hyperglycemia)\n' ...
                    '• **Current Severity:** **Grade %d (%s)** — Model Confidence: %.1f%%\n' ...
                    '• **Triage Classification:** **%s**\n' ...
                    '• **Clinical Urgency:** **%s**\n' ...
                    '• **Pathology Details:** %s\n' ...
                    '• **Recommended Care:** %s'], ...
                    g, gName, g, gName, conf, ...
                    ternary(isRef, 'REFERABLE TO OPHTHALMOLOGIST', 'NON-REFERABLE (ROUTINE CARE)'), ...
                    urg, get_grade_explanation(g, 'en'), get_referral_advice(g, 'en'));
            end
            return;
        else
            if isHindi
                response = sprintf(['👁️ **रोग की जानकारी:**\n\n' ...
                    'यह प्रणाली **डायबिटिक रेटिनोपैथी (Diabetic Retinopathy)** की जांच करती है, जो मधुमेह के रोगियों में दृष्टि हानि का मुख्य कारण है।\n\n' ...
                    '💡 इस मरीज़ की व्यक्तिगत रिपोर्ट और ग्रेड देखने के लिए फंडस फोटो स्कैन करें।']);
            else
                response = sprintf(['👁️ **DISEASE PROFILE:**\n\n' ...
                    'The screened condition is **Diabetic Retinopathy (DR)** — progressive microvascular damage to retinal capillaries from chronic diabetes mellitus.\n\n' ...
                    '💡 *Run AI Screening on a fundus photograph to determine this patient''s specific grade and urgency.*']);
            end
            return;
        end
    end

    % ---------------------------------------------------------------------
    % INTENT 2B: TODAY'S DIAGNOSIS, SEVERITY GRADE & AI TRIAGE
    % ---------------------------------------------------------------------
    if contains(q, {'diagnosis', 'today', 'grade', 'severity', 'stage', 'result', 'finding', 'scan', ...
                   'निदान', 'ग्रेड', 'आज की जांच', 'नतीजा', 'गंभीरता', 'स्टेज'})
        if ~isempty(currentPrediction)
            g = currentPrediction.grade;
            gName = currentPrediction.gradeName;
            conf = currentPrediction.confidence * 100;
            refSc = currentPrediction.referableScore * 100;
            urg = currentPrediction.referralUrgency;
            
            if isHindi
                response = sprintf(['👁️ **आज की रेटिना स्क्रीनिंग का विस्तृत परिणाम (%s):**\n\n' ...
                    '• **रोग का ग्रेड:** **ग्रेड %d — %s**\n' ...
                    '• **एआई विश्वसनीयता (Confidence):** **%.1f%%**\n' ...
                    '• **रेफरल जोखिम स्कोर:** **%.1f%%** (%s)\n' ...
                    '• **क्लिनिकल तात्कालिकता (Urgency):** **%s**\n\n' ...
                    '🔍 **ग्रेड का अर्थ:** %s\n\n' ...
                    '💡 **सिफारिश:** %s'], ...
                    ehr.name, g, gName, conf, refSc, ...
                    ternary(currentPrediction.isReferable, 'रेफरल अनिवार्य', 'सुरक्षित / नियमित वार्षिक जांच'), ...
                    urg, get_grade_explanation(g, 'hi'), get_referral_advice(g, 'hi'));
            else
                response = sprintf(['👁️ **TODAY''S AI SCREENING & SEVERITY ASSESSMENT**\n' ...
                    'Patient: %s (ID: %s | %d %s)\n\n' ...
                    '• **Predicted Severity:** **Grade %d (%s)**\n' ...
                    '• **AI Confidence Score:** **%.1f%%**\n' ...
                    '• **Referable DR Risk Probability:** **%.1f%%** (%s)\n' ...
                    '• **Clinical Urgency Tier:** **%s**\n\n' ...
                    '🔍 **Clinical Meaning of Grade %d:**\n%s\n\n' ...
                    '💡 **Recommended Clinical Action:**\n%s'], ...
                    ehr.name, ehr.id, ehr.age, ehr.sex, ...
                    g, gName, conf, refSc, ...
                    ternary(currentPrediction.isReferable, 'REFERABLE TO OPHTHALMOLOGIST', 'NON-REFERABLE (ROUTINE CARE)'), ...
                    urg, g, get_grade_explanation(g, 'en'), get_referral_advice(g, 'en'));
            end
            return;
        end
    end

    % ---------------------------------------------------------------------
    % INTENT 3: REFERRAL DECISION, URGENCY & HOSPITAL ROUTING
    % ---------------------------------------------------------------------
    if contains(q, {'refer', 'referral', 'urgent', 'urgency', 'hospital', 'send', 'where', 'when to visit', ...
                   'रेफर', 'अस्पताल', 'कब जाएं', 'तात्कालिकता', 'कहाँ भेजें'})
        if ~isempty(currentPrediction)
            isRef = currentPrediction.isReferable;
            urg = currentPrediction.referralUrgency;
            g = currentPrediction.grade;
            
            if isHindi
                if isRef
                    response = sprintf(['🚨 **रेफरल निर्णय: हाँ, मरीज़ को रेफर करना अनिवार्य है!**\n\n' ...
                        '• **वर्तमान स्थिति:** ग्रेड %d (%s)\n' ...
                        '• **रेफरल समय सीमा:** **%s**\n' ...
                        '• **कारण:** आँख के पर्दे (रेटिना) में वैस्कुलर रिसाव और घाव पाए गए हैं, जिससे दृष्टि को खतरा है।\n' ...
                        '• **अनुशंसित अस्पताल:** जिला नेत्र अस्पताल / AIIMS / रीजनल आई इंस्टीट्यूट (विट्रेओ-रेटिनल विशेषज्ञ)।\n\n' ...
                        '📋 **ASHA / स्वास्थ्य कार्यकर्ता हेतु निर्देश:** मरीज़ को डिजिटल रेफरल स्लिप दें और 7 दिन के भीतर फॉलो-अप सुनिश्चित करें।'], ...
                        g, currentPrediction.gradeName, urg);
                else
                    response = sprintf(['✅ **रेफरल निर्णय: अस्पताल रेफर करने की आवश्यकता नहीं है।**\n\n' ...
                        '• **वर्तमान स्थिति:** ग्रेड %d (%s)\n' ...
                        '• **कारण:** आँख में दृष्टि को खतरा पहुँचाने वाले कोई गंभीर घाव या मैक्युलर एडिमा नहीं हैं।\n' ...
                        '• **सिफारिश:** **12 महीने बाद** प्राथमिक स्वास्थ्य केंद्र (PHC) पर वार्षिक नियमित रेटिना जांच। ब्लड शुगर नियंत्रित रखें।'], ...
                        g, currentPrediction.gradeName);
                end
            else
                if isRef
                    response = sprintf(['🚨 **REFERRAL DECISION: YES — CLINICAL REFERRAL REQUIRED (REFERABLE DR)!**\n\n' ...
                        '• **Current Classification:** Grade %d (%s)\n' ...
                        '• **Action Window:** **%s**\n' ...
                        '• **Clinical Rationale:** The fundus presents active microvascular compromise (microaneurysms, hemorrhages, or exudates) that threatens the macula.\n' ...
                        '• **Target Facility:** Secondary or Tertiary Ophthalmology Center (Vitreoretinal Specialty Clinic).\n\n' ...
                        '📋 **Action for PHC Clinician:** Issue the digital bilingual referral slip and schedule transport or appointment alert via Ayushman Bharat Tele-health link.'], ...
                        g, currentPrediction.gradeName, urg);
                else
                    response = sprintf(['✅ **REFERRAL DECISION: NO SPECIALIST REFERRAL REQUIRED (NON-REFERABLE)**\n\n' ...
                        '• **Current Classification:** Grade %d (%s)\n' ...
                        '• **Clinical Rationale:** No vision-threatening lesions, hard exudates, or neovascularization detected.\n' ...
                        '• **Follow-up Protocol:** Annual routine tele-screening in **12 months** at the local PHC. Maintain strict HbA1c (<7.0%%) and blood pressure (<130/80 mmHg).'], ...
                        g, currentPrediction.gradeName);
                end
            end
            return;
        end
    end

    % ---------------------------------------------------------------------
    % INTENT 4: PATHOLOGY — MICROANEURYSMS (MAs)
    % ---------------------------------------------------------------------
    if contains(q, {'microaneurysm', 'ma', 'micro-aneurysm', 'red dot', 'red spot', 'capillary', 'माइक्रोएन्यूरिज्म', 'लाल धब्बे'})
        if isHindi
            response = sprintf(['🔴 **माइक्रोएन्यूरिज्म (Microaneurysms - MAs) क्या होते हैं?**\n\n' ...
                '• **परिभाषा:** यह डायबिटिक रेटिनोपैथी का सबसे प्रारंभिक (Early) क्लिनिकल लक्षण है।\n' ...
                '• **कारण:** लंबे समय तक हाई ब्लड शुगर रहने से रेटिना की सबसे बारीक रक्त नलिकाओं (Capillaries) की सहायक कोशिकाएं (Pericytes) नष्ट हो जाती हैं, जिससे नलिका की दीवार गुब्बारे की तरह फूल जाती है।\n' ...
                '• **दिखने में:** फंडस फोटो में यह छोटे-छोटे गहरे लाल बिंदुओं (Red Dots, 15–25 माइक्रोन) के रूप में दिखाई देते हैं।\n' ...
                '• **जोखिम:** यदि शुगर नियंत्रित न की जाए, तो ये फूटकर रक्तस्राव (Hemorrhages) और द्रव का रिसाव करते हैं।\n\n' ...
                '💡 **इस मरीज़ की स्थिति:** मरीज़ %s में माइक्रोएन्यूरिज्म की उपस्थिति ग्रेड 1 या ग्रेड 2 का संकेत देती है।'], ehr.name);
        else
            response = sprintf(['🔴 **PATHOLOGY: WHAT ARE MICROANEURYSMS (MAs)?**\n\n' ...
                '• **Definition:** Microaneurysms are the earliest clinically visible microscopic hallmark of Diabetic Retinopathy.\n' ...
                '• **Etiology & Mechanism:** Chronic hyperglycemia causes selective apoptosis of capillary pericytes (structural support cells) and weakening of the capillary basement membrane. Intraluminal hydrostatic pressure causes localized focal outpouchings (15–25 µm in diameter).\n' ...
                '• **Ophthalmic Appearance:** Sharp, round, punctate dark-red lesions situated predominantly in the inner nuclear and outer plexiform layers of the retina.\n' ...
                '• **Pathological Significance:** Hyperpermeable endothelial walls leak plasma lipids and fluid into surrounding retinal tissue, directly contributing to retinal thickening and diabetic macular edema (DME).\n\n' ...
                '💡 **Clinical Takeaway for %s:** The presence of microaneurysms confirms microvascular disease and warrants quarterly HbA1c monitoring.'], ehr.name);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 5: PATHOLOGY — HARD EXUDATES & MACULAR EDEMA
    % ---------------------------------------------------------------------
    if contains(q, {'exudate', 'hard exudate', 'lipid', 'yellow', 'dme', 'macular edema', 'csme', 'एक्जुडेट', 'पीले धब्बे', 'मैक्युलर एडिमा'})
        if isHindi
            response = sprintf(['🟡 **हार्ड एक्जुडेट्स (Hard Exudates) व मैक्युलर एडिमा क्या हैं?**\n\n' ...
                '• **परिभाषा:** हार्ड एक्जुडेट्स रेटिना में जमा हुए मोम जैसे पीले रंग के लिपिड (वसा) और लिपोप्रोटीन के जमावड़े होते हैं।\n' ...
                '• **कारण:** क्षतिग्रस्त केशिकाओं से प्लाज्मा और प्रोटीन का रिसाव होकर रेटिना की परतों में जम जाना।\n' ...
                '• **खतरा (DME):** यदि ये एक्जुडेट्स देखने के मुख्य केंद्र (मैक्युला/Fovea) के पास पहुँच जाते हैं, तो इसे **डायबिटिक मैक्युलर एडिमा (DME)** कहते हैं, जो दृष्टि धुंधली होने और अंधेपन का मुख्य कारण है!\n\n' ...
                '💡 **उपचार:** सख्त लिपिड/शुगर नियंत्रण, रेटिना लेजर, अथवा एंटी-VEGF (Anti-VEGF) इंजेक्शन की आवश्यकता होती है।'], '');
        else
            response = sprintf(['🟡 **PATHOLOGY: HARD EXUDATES & DIABETIC MACULAR EDEMA (DME)**\n\n' ...
                '• **Definition:** Hard exudates are waxy, well-defined yellow-white intraretinal deposits composed of lipid-laden macrophages, cholesterol, and serum lipoproteins.\n' ...
                '• **Pathophysiology:** Breakdown of the blood-retinal barrier (BRB) allows chronic extravasation of serum fluids into the outer plexiform layer (Henle''s layer). When water is resorbed, dense insoluble lipids remain precipitated.\n' ...
                '• **Visual Threat (CSME):** When hard exudates form rings (circinate retinopathy) within 500 µm of the foveal center or are accompanied by retinal thickening, it constitutes **Clinically Significant Macular Edema (CSME)**.\n' ...
                '• **Management:** Requires prompt referral for OCT scanning and consideration of intravitreal Anti-VEGF pharmacotherapy (Ranibizumab / Aflibercept) or focal photocoagulation.'], '');
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 6: PATHOLOGY — HEMORRHAGES & COTTON WOOL SPOTS
    % ---------------------------------------------------------------------
    if contains(q, {'hemorrhage', 'bleed', 'blood', 'cotton wool', 'soft exudate', 'रक्तस्राव', 'खून', 'खून का रिसाव'})
        if isHindi
            response = sprintf(['🩸 **रेटिना में रक्तस्राव (Hemorrhages) व कॉटन वूल स्पॉट्स:**\n\n' ...
                '• **डॉट/ब्लॉट रक्तस्राव:** रेटिना की गहरी परतों में कमजोर नलिकाओं के फटने से बनता है (गहरे लाल धब्बे)।\n' ...
                '• **फ्लेम (Flame) रक्तस्राव:** सतही तंत्रिका परत (Nerve Fiber Layer) में रक्त का रिसाव।\n' ...
                '• **कॉटन वूल स्पॉट्स (सफेद धब्बे):** यह वास्तव में रेटिना की धमनियों के बंद होने से हुआ छोटा स्ट्रोक (Micro-infarct) होता है, जहाँ तंत्रिका तंतुओं को ऑक्सीजन नहीं मिलती।\n\n' ...
                '⚠️ **खतरे की घंटी:** यदि 4 में से सभी चतुर्थांशों (Quadrants) में भारी रक्तस्राव हो, तो मरीज तुरंत **सीवियर एनपीडीआर (Grade 3)** में पहुँच जाता है।'], '');
        else
            response = sprintf(['🩸 **PATHOLOGY: RETINAL HEMORRHAGES & COTTON WOOL SPOTS**\n\n' ...
                '• **Dot & Blot Hemorrhages:** Rupture of deep capillaries or microaneurysms within the inner nuclear and outer plexiform layers, presenting as round, circumscribed dark-red lesions.\n' ...
                '• **Flame-Shaped Hemorrhages:** Superficial intraretinal hemorrhages tracking along horizontal nerve fibers in the retinal nerve fiber layer (RNFL).\n' ...
                '• **Cotton Wool Spots (Soft Exudates):** White, fluffy, ill-defined lesions representing localized axoplasmic stasis (micro-infarction) in the RNFL due to terminal arteriolar occlusion.\n\n' ...
                '⚠️ **ETDRS 4-2-1 Staging Rule:** Severe intraretinal hemorrhages in all 4 quadrants herald high risk of progression to proliferative DR within 12 months.'], '');
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 7: GENERAL DISEASE EDUCATION — WHAT IS DR / CAN IT CAUSE BLINDNESS?
    % ---------------------------------------------------------------------
    if contains(q, {'what is diabetic retinopathy', 'what is dr', 'explain dr', 'cause', 'why does it happen', ...
                   'blind', 'blindness', 'lose sight', 'विजन', 'अंधापन', 'डायबिटिक रेटिनोपैथी क्या है', 'बीमारी क्या है'})
        if isHindi
            response = sprintf(['📖 **डायबिटिक रेटिनोपैथी (DR) क्या है और क्या इससे अंधापन हो सकता है?**\n\n' ...
                '• **बीमारी का परिचय:** डायबिटिक रेटिनोपैथी अनियंत्रित डायबिटीज (शुगर) के कारण आँख के पिछले पर्दे (रेटिना) की रक्त नलिकाओं को होने वाला गंभीर नुकसान है।\n' ...
                '• **क्या अंधापन हो सकता है?** **हाँ!** यह कामकाजी वयस्कों में अंधेपन का दुनिया भर में सबसे बड़ा कारण है।\n' ...
                '• **सबसे बड़ा खतरा:** शुरुआती चरणों (ग्रेड 1 व 2) में दर्द या दृष्टि में कोई बदलाव महसूस नहीं होता! जब तक मरीज को धुंधलापन दिखता है, तब तक बीमारी काफी बढ़ चुकी होती है।\n' ...
                '• **अच्छी खबर:** समय रहते नियमित एआई स्क्रीनिंग और सही समय पर लेजर/इंजेक्शन से **90%% से अधिक अंधापन टाला जा सकता है!**'], '');
        else
            response = sprintf(['📖 **DISEASE OVERVIEW: DIABETIC RETINOPATHY & BLINDNESS RISK**\n\n' ...
                '• **What is DR?** Diabetic Retinopathy is a chronic microvascular complication of diabetes mellitus characterized by progressive capillary occlusion, retinal ischemia, vascular leakage, and abnormal neovascular proliferation.\n' ...
                '• **Risk of Blindness:** DR is the leading cause of preventable visual impairment in working-age adults worldwide. Unchecked progression leads to severe vitreous hemorrhage, tractional retinal detachment, and neovascular glaucoma.\n' ...
                '• **The Silent Danger:** Early stages (Grades 1 and 2) are completely asymptomatic — patients experience zero pain and 20/20 vision despite active capillary micro-damage.\n' ...
                '• **Preventability:** Clinical trials (ETDRS, WESDR) demonstrate that **>90%% of severe vision loss is preventable** with timely tele-screening and early intervention.'], '');
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 8: TREATMENT, LASER, INJECTIONS & CLINICAL MANAGEMENT
    % ---------------------------------------------------------------------
    if contains(q, {'treatment', 'how to treat', 'cure', 'laser', 'injection', 'anti-vegf', 'surgery', 'prp', ...
                   'vitrectomy', 'इलाज', 'उपचार', 'लेजर', 'सुई', 'इंजेक्शन', 'ऑपरेशन'})
        if isHindi
            response = sprintf(['💉 **डायबिटिक रेटिनोपैथी का आधुनिक उपचार (Medical Treatment):**\n\n' ...
                '1. **ग्रेड 0 व 1 (शुरुआती):** कोई आँख का ऑपरेशन नहीं। केवल सख्त शुगर (HbA1c < 7.0%%) व बीपी नियंत्रण और वार्षिक जाँच।\n' ...
                '2. **ग्रेड 2 (मध्यम) + एडिमा:** यदि सूजन हो तो आँख में **एंटी-VEGF इंजेक्शन** (Ranibizumab/Aflibercept) या फोकल लेजर।\n' ...
                '3. **ग्रेड 3 व 4 (गंभीर/PDR):** **पैन-रेटिनल फोटोकोएग्युलेशन (PRP लेजर)** जिससे नई खतरनाक रक्त वाहिकाएं सूख जाती हैं।\n' ...
                '4. **उन्नत स्थिति (खून का रिसाव):** विट्रेक्टॉमी (Vitrectomy) सर्जरी द्वारा आँख के अंदर जमा खून को साफ करना।\n\n' ...
                '💡 **याद रखें:** लेजर या इंजेक्शन दृष्टि को वापस 100%% नहीं लाते, बल्कि बची हुई दृष्टि को सुरक्षित रखते हैं। इसलिए जल्दी जाँच सबसे जरूरी है।'], '');
        else
            response = sprintf(['💉 **CLINICAL MANAGEMENT & PHARMACOTHERAPY PROTOCOLS**\n\n' ...
                '1. **Mild to Moderate NPDR (Grades 1–2):**\n' ...
                '   • Medical optimization: HbA1c <7.0%%, BP <130/80 mmHg, statin therapy.\n' ...
                '   • Primary monitoring via fundus tele-screening every 6–12 months.\n\n' ...
                '2. **Diabetic Macular Edema (DME):**\n' ...
                '   • First-line: Intravitreal Anti-VEGF injections (Aflibercept / Ranibizumab / Bevacizumab) to block vascular permeability.\n' ...
                '   • Secondary: Focal/grid argon laser photocoagulation for non-center-involving edema.\n\n' ...
                '3. **Severe NPDR & Proliferative DR (Grades 3–4):**\n' ...
                '   • Panretinal Photocoagulation (PRP Laser): Destroys ischemic peripheral retina to reduce VEGF drive and regress neovascularization.\n' ...
                '   • Pars Plana Vitrectomy (PPV): Indicated for non-clearing vitreous hemorrhage or tractional retinal detachment.'], '');
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 9: HBA1C, BLOOD SUGAR & DIABETIC HISTORY
    % ---------------------------------------------------------------------
    if contains(q, {'hba1c', 'sugar', 'blood sugar', 'glucose', 'fbs', 'ppbs', 'शुगर', 'डायबिटीज', 'ग्लाइकेमिक'})
        if isHindi
            response = sprintf(['🩸 **मरीज़ %s का ब्लड शुगर व HbA1c रिकॉर्ड:**\n\n' ...
                '• **डायबिटीज की अवधि:** **%d वर्ष** से (%s)\n' ...
                '• **हालिया HbA1c स्तर:** **%.1f%%** (तारीख: %s) ⚠️ *खराब नियंत्रण (लक्ष्य: <7.0%%)*\n' ...
                '• **फास्टिंग शुगर (FBS):** **%d mg/dL**\n' ...
                '• **खाने के बाद की शुगर (PPBS):** **%d mg/dL**\n\n' ...
                '⚠️ **क्लिनिकल चेतावनी:** HbA1c %.1f%% सामान्य से बहुत अधिक है। प्रत्येक 1%% अतिरिक्त HbA1c रेटिना क्षति के जोखिम को 35%% बढ़ा देता है! फिजिशियन से मिलकर दवाइयों की खुराक तुरंत बदलवाएं।'], ...
                ehr.name, ehr.diabetesDurationYears, ehr.diabetesType, ...
                ehr.lastHbA1c, ehr.hba1cDate, ehr.fbs, ehr.ppbs, ehr.lastHbA1c);
        else
            response = sprintf(['🩸 **GLYCEMIC PROFILE & DIABETIC HISTORY**\n' ...
                'Patient: %s (ID: %s)\n\n' ...
                '• **Diabetes Duration:** %d years (%s)\n' ...
                '• **Most Recent HbA1c:** **%.1f%%** (Recorded on: %s)\n' ...
                '  *(Standard Clinical Target: <7.0%% — Patient is substantially elevated)*\n' ...
                '• **Fasting Blood Sugar (FBS):** %d mg/dL\n' ...
                '• **Postprandial Blood Sugar (PPBS):** %d mg/dL\n\n' ...
                '⚠️ **Microvascular Impact:** Persistent HbA1c >8.0%% causes progressive glycosylation of vessel walls, pericyte dropout, and accelerates retinal microvascular leakage by over 3x. Immediate glycemic regimen review recommended.'], ...
                ehr.name, ehr.id, ehr.diabetesDurationYears, ehr.diabetesType, ...
                ehr.lastHbA1c, ehr.hba1cDate, ehr.fbs, ehr.ppbs);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 10: BLOOD PRESSURE, HYPERTENSION & KIDNEY/NEPHROPATHY
    % ---------------------------------------------------------------------
    if contains(q, {'bp', 'blood pressure', 'hypertension', 'kidney', 'nephropathy', 'egfr', 'बीपी', 'रक्तचाप', 'किडनी', 'गुर्दे'})
        if isHindi
            response = sprintf(['🩺 **मरीज़ %s का रक्तचाप (BP) व गुर्दे (Kidney) का इतिहास:**\n\n' ...
                '• **उच्च रक्तचाप (Hypertension):** %s\n' ...
                '• **वर्तमान ब्लड प्रेशर:** **%s** (लक्ष्य: <130/80 mmHg)\n' ...
                '• **गुर्दे की स्थिति (Nephropathy):** %s | eGFR: **%s**\n' ...
                '• **हृदय स्वास्थ्य:** %s | कोलेस्ट्रॉल: %s\n\n' ...
                '⚠️ **चिकित्सा संबंध:** अनियंत्रित बीपी और गुर्दे से प्रोटीन का रिसाव (Microalbuminuria) सीधे आँख की बारीक नलिकाओं के फटने और मैक्युला में सूजन को 4 गुना बढ़ा देता है।'], ...
                ehr.name, ehr.hypertension, ehr.bloodPressure, ehr.nephropathy, ehr.eGFR, ...
                ehr.cardiovascular, ehr.dyslipidemia);
        else
            response = sprintf(['🩺 **SYSTEMIC CO-MORBIDITIES & RENAL PROFILE**\n' ...
                'Patient: %s (ID: %s)\n\n' ...
                '• **Hypertension Status:** %s\n' ...
                '• **Current Blood Pressure:** **%s** *(Target: <130/80 mmHg)*\n' ...
                '• **Renal Profile / Diabetic Nephropathy:** %s\n' ...
                '  *(Estimated GFR: %s)*\n' ...
                '• **Cardiovascular Disease:** %s\n' ...
                '• **Lipid Profile (Dyslipidemia):** %s\n\n' ...
                '⚠️ **Clinical Cross-Link:** Diabetic Nephropathy and Retinopathy share identical microvascular pathogenesis. Microalbuminuria serves as a direct surrogate marker for breakdown of the blood-retinal barrier.'], ...
                ehr.name, ehr.id, ehr.hypertension, ehr.bloodPressure, ...
                ehr.nephropathy, ehr.eGFR, ehr.cardiovascular, ehr.dyslipidemia);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 11: PATIENT MEDICATIONS & PHARMACOTHERAPY
    % ---------------------------------------------------------------------
    if contains(q, {'medication', 'medicine', 'prescription', 'drug', 'rx', 'दवा', 'दवाइयां', 'दवाइयाँ', 'दवाई', 'दवाएं', 'गोली'})
        medStr = strjoin(ehr.medications, '\n  • ');
        if isHindi
            response = sprintf(['💊 **मरीज़ %s की वर्तमान दवाइयों की सूची:**\n\n' ...
                '  • %s\n\n' ...
                '• **एलर्जी का विवरण:** %s\n' ...
                '• **पूर्व आँख के इंजेक्शन:** %s\n' ...
                '• **पूर्व रेटिना लेजर:** %s\n\n' ...
                '💡 **निर्देश:** मरीज़ को बताएं कि आँखों की सुरक्षा के लिए शुगर व बीपी की दवाइयां बिना नागा समय पर लेना अनिवार्य है।'], ...
                ehr.name, medStr, ehr.allergies, ehr.priorInjections, ehr.priorLaser);
        else
            response = sprintf(['💊 **ACTIVE MEDICATIONS & PHARMACOTHERAPY AUDIT**\n' ...
                'Patient: %s (ID: %s)\n\n' ...
                '**Current Daily Regimen:**\n  • %s\n\n' ...
                '• **Known Drug Allergies:** %s\n' ...
                '• **Prior Intravitreal Injections:** %s\n' ...
                '• **Prior Laser Photocoagulation:** %s\n\n' ...
                '💡 **Counseling Note:** Emphasize strict compliance with ACE inhibitors (Telmisartan) and statins (Atorvastatin) to reduce microvascular exudation.'], ...
                ehr.name, ehr.id, medStr, ehr.allergies, ehr.priorInjections, ehr.priorLaser);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 12: PRIOR VISITS & LONGITUDINAL CLINICAL TIMELINE
    % ---------------------------------------------------------------------
    if contains(q, {'last visit', 'previous visit', 'history', 'encounter', 'when did he visit', 'पिछली', 'दौरा', 'पिछली जांच'})
        if isHindi
            response = sprintf(['📅 **मरीज़ %s की पिछली विज़िट का विवरण:**\n\n' ...
                '• **पिछली विज़िट की तारीख:** **%s**\n' ...
                '• **जाँच केंद्र:** %s\n' ...
                '• **परीक्षण डॉक्टर:** %s\n' ...
                '• **उस समय का DR ग्रेड:** **%s**\n' ...
                '• **उपचार दिया गया:** %s\n' ...
                '• **डॉक्टर की टिप्पणी:** %s\n\n' ...
                '⚠️ **अनुपालन स्थिति:** %s'], ...
                ehr.name, ehr.visits(1).date, ehr.visits(1).facility, ehr.visits(1).clinician, ...
                ehr.visits(1).drGrade, ehr.visits(1).treatmentGiven, ehr.visits(1).clinicalNotes, ...
                ehr.complianceAlert);
        else
            visitStr = {};
            for v = 1:numel(ehr.visits)
                vt = ehr.visits(v);
                visitStr{end+1} = sprintf('**Encounter #%d (%s):**\n  • Facility: %s  |  Doctor: %s\n  • Grade: %s  |  Rx: %s\n  • Notes: %s', ...
                    v, vt.date, vt.facility, vt.clinician, vt.drGrade, vt.treatmentGiven, vt.clinicalNotes);
            end
            response = sprintf(['📅 **LONGITUDINAL VISIT HISTORY & ENCOUNTERS**\n' ...
                'Patient: %s (ID: %s)\n\n' ...
                '• **Last Screening Date:** **%s**\n' ...
                '• **Visit Compliance Status:** %s\n\n' ...
                '**Detailed Visit Records:**\n%s'], ...
                ehr.name, ehr.id, ehr.lastVisitDate, ehr.complianceAlert, strjoin(visitStr, '\n\n'));
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 13: DIET, EXERCISE & LIFESTYLE COUNSELING
    % ---------------------------------------------------------------------
    if contains(q, {'diet', 'food', 'lifestyle', 'exercise', 'walk', 'nutrition', 'आहार', 'खान-पान', 'व्यायाम', 'खाना'})
        if isHindi
            response = sprintf(['🥗 **ग्रामीण मधुमेह रोगियों के लिए आँखों की सुरक्षा हेतु आहार व जीवनशैली:**\n\n' ...
                '1. **आहार में क्या घटाएं:** सफेद चावल, मैदा, चीनी, गुड़, आलू और तली-भुनी चीजों का सेवन कम करें।\n' ...
                '2. **आहार में क्या बढ़ाएं:** हरी पत्तेदार सब्जियां (पालक, मेथी), जामुन, करेला, दालें और अंकुरित अनाज खाएं।\n' ...
                '3. **दैनिक व्यायाम:** प्रतिदिन कम से कम 30 मिनट तेज गति से पैदल चलें।\n' ...
                '4. **व्यसन से दूरी:** बीड़ी, सिगरेट और तंबाकू का सेवन तुरंत बंद करें — यह रेटिना की नसों को सिकोड़कर नुकसान को 3 गुना तेज करता है!\n' ...
                '5. **नियमित जांच:** कोई भी लक्षण न होने पर भी हर साल प्राथमिक केंद्र पर आँख की फोटो खिंचवाएं।'], '');
        else
            response = sprintf(['🥗 **CLINICAL NUTRITION & LIFESTYLE RECOMMENDATIONS**\n\n' ...
                '1. **Glycemic Diet Control:** Restrict high-glycemic carbohydrates (polished white rice, refined flour, refined sugars). Increase dietary soluble fiber (fenugreek, lentils, green leafy vegetables).\n' ...
                '2. **Physical Activity:** 150 minutes per week of moderate-intensity aerobic exercise (e.g. 30 minutes brisk walking 5 days/week) to improve insulin sensitivity.\n' ...
                '3. **Tobacco Cessation:** Absolute cessation of smoking, bidi, and smokeless tobacco. Nicotine causes acute vasoconstriction and doubles the rate of progression to proliferative DR.\n' ...
                '4. **Blood Pressure / Sodium:** Restrict dietary salt to <5 grams/day to reduce hydrostatic stress on fragile retinal capillary walls.'], '');
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 14: PATIENT DEMOGRAPHICS & BASIC IDENTITY
    % ---------------------------------------------------------------------
    if contains(q, {'patient name', 'who is patient', 'patient id', 'age', 'sex', 'gender', 'मरीज का नाम', 'उम्र', 'आईडी'})
        if isHindi
            response = sprintf(['👤 **मरीज़ की पहचान व जनसांख्यिकीय विवरण:**\n\n' ...
                '• **नाम:** **%s**\n' ...
                '• **मरीज़ आईडी:** `%s`\n' ...
                '• **उम्र:** %d वर्ष\n' ...
                '• **लिंग:** %s\n' ...
                '• **प्राथमिक स्वास्थ्य केंद्र (PHC):** %s\n' ...
                '• **आयुष्मान भारत आईडी:** ABHA-91-8842-1092\n' ...
                '• **पंजीकृत संपर्क:** +91 98765 43210 (गाँव: निपाणी, जिला: नांदेड़)'], ...
                ehr.name, ehr.id, ehr.age, ehr.sex, ehr.phc);
        else
            response = sprintf(['👤 **PATIENT DEMOGRAPHICS & PROFILE**\n\n' ...
                '• **Full Name:** **%s**\n' ...
                '• **Patient ID:** `%s`\n' ...
                '• **Age / Gender:** %d years  |  %s\n' ...
                '• **Primary Health Center (PHC):** %s\n' ...
                '• **ABHA Health Card ID:** ABHA-91-8842-1092\n' ...
                '• **Registered Contact:** +91 98765 43210 (Village: Nipani, District: Nanded)'], ...
                ehr.name, ehr.id, ehr.age, ehr.sex, ehr.phc);
        end
        return;
    end

    % ---------------------------------------------------------------------
    % INTENT 15: SMART CONCISE FALLBACK (DIRECT GUIDANCE, NO RANDOM DUMP)
    % ---------------------------------------------------------------------
    if isHindi
        response = sprintf(['🤖 **रेटिनाकेयर क्लिनिकल एआई:**\n\n' ...
            'मैं आपके प्रश्न *"%s"* को समझ नहीं पाया। कृपया नीचे दिए गए विशिष्ट विषयों में से पूछें:\n\n' ...
            '• **बीमारी व निदान:** "मरीज को क्या बीमारी है?", "आज का ग्रेड क्या है?"\n' ...
            '• **रेफरल व अस्पताल:** "क्या मरीज को रेफर करना चाहिए?", "रेफरल कितना जरूरी है?"\n' ...
            '• **इतिहास व जांच:** "मरीज का HbA1c क्या है?", "वर्तमान दवाइयाँ क्या हैं?"\n' ...
            '• **इलाज व सलाह:** "ग्रेड 2 का इलाज क्या है?", "माइक्रोएन्यूरिज्म क्या होता है?"'], ...
            userQuery);
    else
        response = sprintf(['🤖 **RETINACARE CLINICAL AI ASSISTANT:**\n\n' ...
            'I didn''t fully recognize the specific question: *"%s"*.\n' ...
            'Please ask a direct clinical question such as:\n\n' ...
            '• **Diagnosis & Disease:** "What disease does the patient have?", "What is today''s DR grade?"\n' ...
            '• **Triage & Routing:** "Is this patient referable?", "How urgent is the referral?"\n' ...
            '• **Medical History:** "What is the patient''s HbA1c?", "What are their active medications?"\n' ...
            '• **Pathology & Care:** "What is a microaneurysm?", "What treatment is recommended?"'], ...
            userQuery);
    end
end

% -------------------------------------------------------------------------
% Helper: Call Google Gemini REST API
% -------------------------------------------------------------------------
function apiResp = call_gemini_api(userQuery, ehr, pred, etdrs, activeLang, config)
    apiResp = '';
    apiKey = '';
    if isfield(config, 'gemini_api_key') && ~isempty(config.gemini_api_key)
        apiKey = strtrim(config.gemini_api_key);
    end
    if isempty(apiKey)
        apiKey = getenv('GEMINI_API_KEY');
    end
    if isempty(apiKey), return; end

    model = 'gemini-2.5-flash';
    if isfield(config, 'model') && ~isempty(config.model)
        model = config.model;
    end

    % Build concise patient context prompt
    ctx = sprintf(['Patient Context:\n' ...
        '- Name: %s, Age: %d, Sex: %s, ID: %s\n' ...
        '- Diabetes Duration: %d yrs (%s), Last HbA1c: %.1f%% (Date: %s)\n' ...
        '- Blood Pressure: %s, Hypertension: %s, Nephropathy: %s\n' ...
        '- Active Medications: %s\n'], ...
        ehr.name, ehr.age, ehr.sex, ehr.id, ...
        ehr.diabetesDurationYears, ehr.diabetesType, ehr.lastHbA1c, ehr.hba1cDate, ...
        ehr.bloodPressure, ehr.hypertension, ehr.nephropathy, ...
        strjoin(ehr.medications, ', '));

    if ~isempty(pred)
        ctx = [ctx, sprintf(['- Today''s Retinal Scan: Grade %d (%s), Confidence: %.1f%%, Referable Risk: %.1f%%, Urgency: %s, Is Referable: %s\n'], ...
            pred.grade, pred.gradeName, pred.confidence*100, pred.referableScore*100, ...
            pred.referralUrgency, ternary(pred.isReferable, 'YES', 'NO'))];
    end
    if ~isempty(etdrs) && isfield(etdrs, 'etdrsStage')
        ctx = [ctx, sprintf('- ETDRS Staging: %s\n', etdrs.etdrsStage)];
    end

    langNote = 'Answer in English.';
    if strcmp(activeLang, 'hi') || contains(lower(userQuery), {'hindi', 'हिन्दी'})
        langNote = 'Answer in natural, professional Hindi (Devanagari script).';
    elseif strcmp(activeLang, 'mr')
        langNote = 'Answer in Marathi.';
    elseif strcmp(activeLang, 'kn')
        langNote = 'Answer in Kannada.';
    end

    sysPrompt = sprintf(['You are RetinaCare AI, an expert clinical tele-ophthalmology assistant at an Indian rural Primary Health Centre (PHC).\n' ...
        'Answer the user''s question directly, accurately, and concisely based strictly on the patient data provided.\n' ...
        'STRICT CLINICAL RULES:\n' ...
        '1. Answer ONLY what the user asked. Do NOT dump the patient''s entire record or medication list unless asked.\n' ...
        '2. Keep answers focused, clear, and direct (2-4 bullet points or short paragraphs).\n' ...
        '3. If asked about disease or condition, state clearly that the disease is Diabetic Retinopathy and explain its stage.\n' ...
        '4. %s\n\n' ...
        '%s\n\n' ...
        'Clinician Question: %s'], langNote, ctx, userQuery);

    url = sprintf('https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s', model, apiKey);

    payload = struct('contents', struct('parts', struct('text', sysPrompt)));

    try
        options = weboptions('MediaType', 'application/json', 'Timeout', 10, 'RequestMethod', 'post');
        rawResp = webwrite(url, payload, options);
        if isfield(rawResp, 'candidates') && ~isempty(rawResp.candidates)
            c = rawResp.candidates(1);
            if isfield(c, 'content') && isfield(c.content, 'parts') && ~isempty(c.content.parts)
                apiResp = char(c.content.parts(1).text);
            end
        end
    catch ME
        apiResp = '';
    end
end

% -------------------------------------------------------------------------
% Helper Sub-Functions
% -------------------------------------------------------------------------
function s = ternary(cond, valTrue, valFalse)
    if cond, s = valTrue; else, s = valFalse; end
end

function expStr = get_grade_explanation(grade, lang)
    switch grade
        case 0
            if strcmp(lang, 'hi')
                expStr = 'आँख का पर्दा पूरी तरह स्वस्थ है। कोई रक्तस्राव या रिसाव नहीं मिला है।';
            else
                expStr = 'Normal fundus with intact capillary beds, no microaneurysms, and clear macula.';
            end
        case 1
            if strcmp(lang, 'hi')
                expStr = 'शुरुआती डायबिटिक रेटिनोपैथी। केवल कुछ छोटे माइक्रोएन्यूरिज्म (खून के बिंदु) मौजूद हैं। दृष्टि को खतरा नहीं है।';
            else
                expStr = 'Mild Non-Proliferative DR. Characterized by isolated microaneurysms only, without exudates.';
            end
        case 2
            if strcmp(lang, 'hi')
                expStr = 'मध्यम डायबिटिक रेटिनोपैथी। माइक्रोएन्यूरिज्म के साथ पीले एक्जुडेट्स और छोटे रक्तस्राव पाए गए हैं। मैक्युला को खतरा हो सकता है।';
            else
                expStr = 'Moderate NPDR. Presence of microaneurysms, blot hemorrhages, or hard exudates, requiring retinal consultation.';
            end
        case 3
            if strcmp(lang, 'hi')
                expStr = 'गंभीर डायबिटिक रेटिनोपैथी (Severe NPDR)। रेटिना के बड़े हिस्से में खून की नलियां बंद हो चुकी हैं। तुरंत उपचार न मिलने पर दृष्टि जा सकती है।';
            else
                expStr = 'Severe NPDR. Marked capillary non-perfusion across multiple quadrants (ETDRS 4-2-1 rule), high risk of proliferative conversion.';
            end
        case 4
            if strcmp(lang, 'hi')
                expStr = 'प्रोलिफेरेटिव डायबिटिक रेटिनोपैथी (PDR)। आँख में नई कमजोर नलियां उग आई हैं जिनसे कभी भी भारी रक्तस्राव हो सकता है। अति-आवश्यक स्थिति!';
            else
                expStr = 'Proliferative DR (PDR). Fragile neovascularization present on disc or retina, acute threat of vitreous hemorrhage or retinal detachment.';
            end
        otherwise
            expStr = 'Standard clinical grading.';
    end
end

function advStr = get_referral_advice(grade, lang)
    switch grade
        case 0
            if strcmp(lang, 'hi')
                advStr = 'वार्षिक नियमित रेटिना जांच (12 महीने बाद)। ब्लड शुगर व बीपी का सामान्य स्तर बनाए रखें।';
            else
                advStr = 'Routine annual tele-screening in 12 months. Maintain strict HbA1c <7.0% and annual exam.';
            end
        case 1
            if strcmp(lang, 'hi')
                advStr = '6 से 12 महीने में दोबारा जांच कराएं। फिजिशियन से मिलकर शुगर की दवाइयों की समीक्षा करें।';
            else
                advStr = 'Follow-up screening in 6–12 months. Optimize glycemic and blood pressure management.';
            end
        case 2
            if strcmp(lang, 'hi')
                advStr = '30 दिन के भीतर जिला अस्पताल के नेत्र रोग विशेषज्ञ (Ophthalmologist) से विस्तृत जांच कराएं।';
            else
                advStr = 'Refer to secondary ophthalmology clinic within 30 days for slit-lamp biomicroscopy and OCT assessment.';
            end
        case 3
            if strcmp(lang, 'hi')
                advStr = 'अति-शीघ्र (7 से 14 दिन के भीतर) विट्रेओ-रेटिनल विशेषज्ञ से मिलें। लेजर उपचार (PRP) की आवश्यकता हो सकती है।';
            else
                advStr = 'Urgent referral within 7–14 days to a vitreoretinal specialist. High indication for panretinal laser.';
            end
        case 4
            if strcmp(lang, 'hi')
                advStr = 'आपातकालीन रेफरल (24 से 48 घंटे के भीतर)। तुरंत टर्शियरी आई केयर सेंटर पर लेजर या सर्जरी करवाएं!';
            else
                advStr = 'EMERGENCY 48-HOUR REFERRAL to tertiary retinal care. Urgent anti-VEGF injection and PRP laser indicated.';
            end
        otherwise
            advStr = 'Follow ophthalmologist instructions.';
    end
end
